services:
  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one
    ports:
      - "16686:16686"
    environment:
      -   COLLECTOR_OTLP_ENABLED="true"

  otelcol:
    container_name: otelcol
    image: otel/opentelemetry-collector-contrib
    ports:
      - "4317:4317"
    volumes:
      - otelcol\config.yaml:/etc/otelcol-contrib/config.yaml

  otel-javaagent:
    container_name: otel-javaagent
    image: psoorej/oteljavaagent
    command: "sleep infinity"
    volumes:
      - shared-volume:/opt/opentelemetry

  testotel1:
    container_name: testotel1
    image: psoorej/testotel1
    ports:
      - "8888:8080"
    volumes:
     - shared-volume:/usr/local/OTELAgent
    environment:
      - JAVA_TOOL_OPTIONS="-javaagent:/usr/local/OTELAgent/opentelemetry-javaagent.jar"
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otelcol:4317
      - OTEL_METRICS_EXPORTER=none
      - OTEL_SERVICE_NAME=testOTEL1

  testotel:
    container_name: testotel
    image: psoorej/testotel
    ports:
      - "8889:8080"
    volumes:
      - shared-volume:/usr/local/OTELAgent
    environment:
      - OTEL_SERVICE_NAME=testOTEL
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otelcol:4317
      - OTEL_METRICS_EXPORTER=none
      - JAVA_TOOL_OPTIONS="-javaagent:/usr/local/OTELAgent/opentelemetry-javaagent.jar"

volumes:
  shared-volume: