extensions:
  memory_ballast:
    size_mib: 512
  zpages:
    endpoint: localhost:55679

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: otelcol:4317
      http:
        endpoint: otelcol:4318

processors:
  batch:
  memory_limiter:
    # 75% of maximum memory up to 4G
    limit_mib: 1536
    # 25% of limit up to 2G
    spike_limit_mib: 512
    check_interval: 5s

exporters:
  jaeger: # the Jaeger exporter, to ingest traces to backend
    endpoint: "jaeger:14250"
    tls:
      insecure: true
  logging:
    verbosity: detailed

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [jaeger]
#    metrics:
#     receivers: [otlp]
#     processors: [batch]
#     exporters: [logging]

  extensions: []